DoctrineServiceProvider:
  db.options:
    driver: pdo_mysql
    dbname: scrilex
    host: localhost
    user: root
    password: root
    
DoctrineORMServiceProvider:
  db.orm.entities:
    0:
      type: annotation
      path: %root%/src/Scrilex/Entity
      namespace: Scrilex\Entity
  db.orm.proxies_dir: %root%/cache/doctrine/Proxy
  db.orm.auto_generate_proxies: true
  
MonologServiceProvider:
  monolog.logfile: %root%/development.log
  
TwigServiceProvider:
  twig.path:
    - %root%/src/Resources/views
    - %root%/vendor/amenophis/silex-useradmin/src/Resources/views
  twig.form.templates:
    - form_div_layout_bootstrap.html.twig
  
TranslationServiceProvider:
  translator.messages: []
  
SerializerServiceProvider:
  serializer.src_directory: %root%/vendor/jms/serializer-bundle
  serializer.cache.directory: %root%/cache/serializer

Amenophis:
  useradmin:
    user:
      list:
        columns:
          username:
            label: Username
          firstname: 
            label: Firstname
          lastname:
            label: Lastname
          isManager: 
            label: Manager
            type: bool
            attrs:
              width: 70px
          isAdmin:
            label: Admin
            type: bool
            attrs:
              width: 70px
        actions:
          edit:
            label: ""
            type: ajax
            options:
              route: admin_user_edit
              modalTitle: Edit {{ user.firstname }} {{ user.lastname }} ({{ user.username }})
            attrs:
              width: 16px
          delete:
            label: ""
            type: confirm
            options:
              route: admin_user_delete
            attrs:
              width: 16px
            
          
      class: Scrilex\Entity\User
      form:
        add: Scrilex\Form\UserAdd
        edit: Scrilex\Form\UserEdit
  default_password: foo